# Generated by Django 3.0.7 on 2020-11-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20201114_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(default='images/default/default-user-img.png', upload_to='avatar/'),
        ),
    ]
