# Generated by Django 3.0.7 on 2020-11-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_teacher_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.BooleanField(default=False),
        ),
    ]
