# Generated by Django 3.0.7 on 2020-11-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='degree_level',
            field=models.CharField(choices=[('+2', '+2'), ('developma', 'Developma'), ('bachler', 'Bachler'), ('master', 'Master')], default=1, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('science', 'Science'), ('management', 'Management'), ('other', 'Other')], default=1, max_length=50),
        ),
    ]
