# Generated by Django 3.0.7 on 2020-11-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_auto_20201123_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcourse',
            name='part',
            field=models.CharField(blank=True, choices=[('1', 'First Part'), ('2', 'Second Part')], default=1, max_length=10),
        ),
    ]
