# Generated by Django 3.0.7 on 2020-11-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_auto_20201123_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRegisterCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Course')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='college.Teacher')),
            ],
        ),
    ]
