# Generated by Django 3.0.7 on 2020-11-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_teacherregistercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
