# Generated by Django 3.0.7 on 2020-12-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_assignsubject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignsubject',
            unique_together={('teacher', 'subject', 'course')},
        ),
    ]
