# Generated by Django 3.0.7 on 2020-12-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_auto_20201201_1705'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignsubject',
            unique_together=set(),
        ),
    ]
