# Generated by Django 3.0.7 on 2020-12-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0016_auto_20201202_1451'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectcourse',
            unique_together=set(),
        ),
    ]
