# Generated by Django 3.0.7 on 2020-12-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_auto_20201205_1017'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectcourse',
            unique_together={('course', 'subject')},
        ),
    ]
