# Generated by Django 3.0.7 on 2020-12-05 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_auto_20201205_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubject',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.Course'),
        ),
        migrations.AlterField(
            model_name='assignsubject',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.Subject'),
        ),
    ]
