# Generated by Django 3.1.4 on 2020-12-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0021_auto_20201215_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=1, max_length=30),
        ),
    ]
